services:
  backend:
      image: forring7/gender_analysis_vision_python_server:tagname
      container_name: python_backend
      ports:
        - "8000:8000"  # 백엔드 서비스가 외부에서 접근 가능한 포트 설정
      depends_on:
        - loki  # 필요시 Loki에 의존성을 추가 (예: 로그 전송 시)

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - ./loki_data:/wal
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
      # 로컬
      - /Users/highbuff/Repository/gender_analysis_vision/logs:/Users/highbuff/Repository/gender_analysis_vision/logs
    command: -config.file=/etc/promtail/config.yml
    depends_on:
    - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: