server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
# AWS EC2
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  
  # 로컬 로그
  - job_name: localLog
    static_configs:
    - targets:
      - localhost
      labels:
        job: localhost
        __path__: /Users/highbuff/Repository/gender_analysis_vision/logs/localLog.log
