name: Deploy Dockerized Python App to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 최신 코드를 가져옴

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        # run: docker build -t your-docker-repo/gender_analysis_vision:latest .
        run: docker build -t forring7/gender_analysis_vision_python_server:1.0.0 .

      - name: Push Docker image to Docker Hub
        run: docker push forring7/gender_analysis_vision_python_server:1.0.0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # GitHub Secrets에 저장된 SSH 키 사용

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
            if [ ! -d "/home/ec2-user/gender_analysis_vision" ]; then
              git clone https://github.com/blackjune67/gender_analysis_vision.git /home/ec2-user/gender_analysis_vision
            fi
            cd /home/ec2-user/gender_analysis_vision

            # Docker Compose 파일을 사용해 컨테이너 실행
            docker-compose down  # 기존 컨테이너 종료
            docker-compose pull   # 최신 Docker 이미지 가져오기
            docker-compose up -d  # Docker Compose로 애플리케이션 실행
          EOF
